### ISSUE TITLE
Getting 'Cannot switch to old mode now.' Error while running this.

### ISSUE THREAD

**Issue by sambhav-gore** [mdunisch/lololodash#24]
Here is the full error I am getting while running lololodash:

```shell
_stream_readable.js:730
    throw new Error('Cannot switch to old mode now.');
          ^
Error: Cannot switch to old mode now.
    at emitDataEvents (_stream_readable.js:730:11)
    at ReadStream.Readable.resume (_stream_readable.js:715:3)
    at showMenu (/usr/local/lib/node_modules/lololodash/node_modules/workshopper/menu.js:90:17)
    at showMenu (/usr/local/lib/node_modules/lololodash/node_modules/workshopper/exerciseMenu.js:29:10)
    at Workshopper.printMenu (/usr/local/lib/node_modules/lololodash/node_modules/workshopper/workshopper.js:355:14)
    at new Workshopper (/usr/local/lib/node_modules/lololodash/node_modules/workshopper/workshopper.js:180:8)
    at Workshopper (/usr/local/lib/node_modules/lololodash/node_modules/workshopper/workshopper.js:22:12)
    at Object.<anonymous> (/usr/local/lib/node_modules/lololodash/lololodash.js:16:1)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
```

I also got some warnings during the installation itself.

**Comment by mdunisch** [comment]
hi @sambhav-gore: You you post the warnings during installation also? And what node.js-version you are using (type `node -v` to display)?

**Comment by sambhav-gore** [comment]
Node version is `0.10.20`
NPM version is  `2.6.0`
This is the warning 

```shell
npm WARN unmet dependency /usr/local/lib/node_modules/karma/node_modules/http-proxy requires colors@'0.x.x' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/karma/node_modules/colors,
npm WARN unmet dependency which is version 0.6.0-1
npm WARN unmet dependency /usr/local/lib/node_modules/meanio/node_modules/bower/node_modules/tar-fs/node_modules/tar-stream/node_modules/bl requires readable-stream@'~1.0.26' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/meanio/node_modules/bower/node_modules/tar-fs/node_modules/tar-stream/node_modules/readable-stream,
npm WARN unmet dependency which is version 1.0.33-1
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/phonegap-build requires colors@'0.6.x' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/colors,
npm WARN unmet dependency which is version 0.6.0-1
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/prompt/node_modules/winston requires colors@'0.x.x' but will load
npm WARN unmet dependency /usr/local/lib/node_modules/phonegap/node_modules/colors,
npm WARN unmet dependency which is version 0.6.0-1
lololodash@0.5.3 /usr/local/lib/node_modules/lololodash
├── diff@1.3.2
├── lodash@3.6.0
├── moment@2.10.2
├── workshopper-exercise@2.3.0 (after@0.8.1, visualwidth@0.0.1, chalk@0.4.0, xtend@2.1.2, split@0.3.3, tuple-stream@0.0.2, i18n-core@1.3.3, through2@0.4.2)
├── workshopper@2.4.0 (map-async@0.1.1, xtend@3.0.0, mkdirp@0.3.5, visualwidth@0.0.1, chalk@0.4.0, colors-tmpl@0.1.1, i18n-core@1.3.3, optimist@0.6.1, terminal-menu@2.1.1, msee@0.1.1)
└── update-notifier@0.3.2 (is-npm@1.0.0, semver-diff@2.0.0, string-length@1.0.0, chalk@1.0.0, configstore@0.3.2, latest-version@1.0.0)
```

**Comment by riyadhalnur** [comment]
have you tried upgrading your node version? some deps might require you to use newer versions of node

**Comment by mdunisch** [comment]
close, user don't answer
